"""Update tasks' parent_task_id field

Revision ID: 5b32651a8f08
Revises: cd5dbb8ed144
Create Date: 2023-12-04 23:18:20.378575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b32651a8f08'
down_revision: Union[str, None] = 'cd5dbb8ed144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
